
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: sls_development

test:
  <<: *default
  database: sls_test

production:
  <<: *default
  database: sls_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['SLS_DATABASE_PASSWORD'] %>
